package:
  name: "bftools"
  version: "6.5.0"

build:
  noarch: generic
  number: 1

source:
  url: https://downloads.openmicroscopy.org/bio-formats/6.5.0/artifacts/bftools.zip
  sha256: fbe9fd9c7d445e152c48eb0841e4519591f6dc97471c854eba250406f8389d44

requirements:
  host:
  run:
    - openjdk

test:
  commands:
    - showinf -nopix a.fake

extra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats command line tools
  doc_url: https://docs.openmicroscopy.org/bio-formats/latest/users/comlinetools/index.html
  dev_url: https://github.com/ome/bioformats
